# Generated by Django 3.2.4 on 2021-06-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='sentiment',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10),
        ),
    ]
