# Generated by Django 3.2.4 on 2021-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0002_alter_testmodel_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='github'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='introduction',
            field=models.TextField(max_length=10000, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='name', max_length=20, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='twitter',
            field=models.CharField(max_length=100, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
