# Generated by Django 3.2.4 on 2021-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0005_auto_20210624_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='github',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='job',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='Please input your name', max_length=10),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
