# Generated by Django 3.2.4 on 2021-06-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0008_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='kaggle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='img/upload'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
