# Generated by Django 3.2.4 on 2021-06-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0010_auto_20210626_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
