# Generated by Django 3.2.4 on 2021-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0011_alter_imagemodel_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='kaggle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
