# Generated by Django 3.2.4 on 2021-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpapp', '0017_artmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmodel',
            name='script',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='artmodel',
            name='summary',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
