# Generated by Django 3.2.4 on 2021-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210622_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='files',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='number',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='job',
            field=models.TextField(blank=True, null=True, verbose_name='仕事'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='introduction',
            field=models.TextField(verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter'),
        ),
    ]
