# Generated by Django 3.2.4 on 2021-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210624_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'male'), ('woman', 'female')], max_length=10),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
