# Generated by Django 3.2.4 on 2021-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210626_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='kaggle',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='note',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
