# Generated by Django 3.2.4 on 2021-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_imagemodel_signate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyScenarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Please input text', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(blank=True, choices=[('a_month', '一ヶ月程度'), ('some_month', '二ヶ月から三ヶ月程'), ('half_month', '半年程'), ('a_year', '一年程')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
