# Generated by Django 3.2.4 on 2021-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_myscenariomodel_skillmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='period',
            field=models.CharField(blank=True, choices=[('一ヶ月程度', '一ヶ月程度'), ('二ヶ月から三ヶ月程', '二ヶ月から三ヶ月程'), ('半年程', '半年程'), ('一年程', '一年程')], max_length=20),
        ),
    ]
