# Generated by Django 3.2.4 on 2021-06-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_skillmodel_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='myscenariomodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
