# Generated by Django 3.1.7 on 2022-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210628_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('script', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyScenarioModel',
            new_name='SelfIntroductionModel',
        ),
        migrations.DeleteModel(
            name='ArtModel',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='img/upload'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.TextField(default='Welcome to my site!!', max_length=200),
        ),
    ]
