# Generated by Django 3.1.7 on 2022-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20220823_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introductionmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='introductionmodel',
            name='script',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
