# Generated by Django 3.1.7 on 2022-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20220823_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionmodel',
            name='name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
