# Generated by Django 3.1.7 on 2022-10-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='period',
            field=models.CharField(blank=True, choices=[('一ヶ月程度', '一ヶ月程度'), ('二ヶ月から三ヶ月程', '二ヶ月から三ヶ月程'), ('半年程', '半年程'), ('一年程', '一年程'), ('一年以上', '一年以上')], max_length=20),
        ),
    ]
