# Generated by Django 3.1.7 on 2022-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20221024_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='icon_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
