# Generated by Django 3.1.7 on 2022-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_skillmodel_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='kaggle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
